// examples/vite/src/Superfluid.tsx
"use client"

import { useReadCfa } from "sdk/wagmi/protocol"
import { mainnet } from "wagmi/chains"

export function Superfluid() {
    const { data, isLoading, isError } = useReadCfa({
        chainId: mainnet.id,
        functionName: "MAXIMUM_FLOW_RATE"
    })

    return (
        <div>
            {isLoading && <p>Loading...</p>}
            {isError && <p>Error loading</p>}
            {data && (
                <div>
                    <h3>CFA Maximum Flow Rate:</h3>
                    <p>{data.toString()}</p>
                </div>
            )}
        </div>
    )
}

// examples/vue/src/components/Superfluid.vue
<script setup lang="ts">
import { cfaAbi, cfaAddress } from "sdk/protocol"
import { useAccount, useReadContract } from "@wagmi/vue"
import { computed } from "vue"

const { chainId, isConnected } = useAccount()

const cfaAddressOnChain = computed(() => cfaAddress[chainId.value as keyof typeof cfaAddress])

const { data, isLoading, isError } = useReadContract({
    address: cfaAddressOnChain,
    abi: cfaAbi,
    functionName: "MAXIMUM_FLOW_RATE",
    query: {
      enabled: !!cfaAddressOnChain
    }
})
</script>

<template>
  <h2>Superfluid</h2>

  <div v-if="isConnected">
    CFA Maximum Flow Rate:
    <span v-if="!cfaAddressOnChain">CFA not deployed on this chain</span>
    <span v-else-if="isLoading">Loading...</span>
    <span v-else-if="isError">Error</span>
    <span v-else>{{ data }}</span>
  </div>
  <div v-else>
    Connect wallet to see Superfluid info.
  </div>

</template>
